[program:ddns-ipv6-webui]
command = /main/app/github/ddns-ipv6/venv/bin/uvicorn app.webui:app --host 0.0.0.0 --port 5080
directory = /main/app/github/ddns-ipv6
autostart = true
autorestart = true
startretries = 1000000
startsecs = 3
exitcodes = 0,2
stdout_logfile = /main/log/app/ddns-ipv6-webui.log
stdout_logfile_maxbytes = 1MB
stdout_logfile_backups = 0
stdout_capture_maxbytes = 0
redirect_stderr = true
