[program:ddns-ipv6]
command = /main/app/github/ddns-ipv6/venv/bin/python3 ddns.py
directory = /main/app/github/ddns-ipv6
autostart = true
autorestart = true
startretries = 1000000
startsecs = 5
exitcodes = 0,2
user = root
stdout_logfile = /main/log/app/ddns-ipv6.log
stdout_logfile_maxbytes = 1MB
stdout_logfile_backups = 0
stdout_capture_maxbytes = 0
redirect_stderr = true
